services:
  db-bank:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=atm_user
      - MYSQL_PASSWORD=pankkipass
      - MYSQL_ROOT_PASSWORD=notneeded
      - MYSQL_DATABASE=bank_automat
    volumes:
      # Suoritusjärjestys: bank_automat, testdata, procedures
      - ./sql/bank_automat.sql:/docker-entrypoint-initdb.d/1-bank_automat.sql
      - ./sql/testdata.sql:/docker-entrypoint-initdb.d/2-testdata.sql
      - ./sql/procedures.sql:/docker-entrypoint-initdb.d/3-procedures.sql
